# Generated by Django 4.2.9 on 2024-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Author Name', max_length=100)),
                ('university', models.CharField(default='Name of the University', max_length=100)),
                ('department', models.CharField(default='Name of the Department', max_length=100)),
                ('email', models.EmailField(default='Enter your email address', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorialboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefix', models.CharField(default='Prof', max_length=20)),
                ('FirstName', models.CharField(default='Tom', max_length=100)),
                ('SecondName', models.CharField(default='Kwanya', max_length=100)),
                ('University', models.CharField(default='Technical University of Kenya', max_length=100)),
                ('Country', models.CharField(default='Kenya', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editorinchief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='Tom', max_length=100)),
                ('University', models.CharField(default='Technical University of Kenya', max_length=100)),
                ('Department', models.CharField(default='Information and library Sciences', max_length=100)),
                ('MyEmail', models.CharField(default='tom.kwanya@gmail.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submit_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=100)),
                ('doc_file', models.FileField(upload_to='rjikm/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=400)),
                ('volume', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2022)),
                ('abstract_title', models.CharField(default='Abstract', max_length=100)),
                ('abstract', models.TextField(default='No abstract provided')),
                ('keyword_title', models.CharField(default='Keyword', max_length=100)),
                ('keywords', models.CharField(default='None', max_length=200)),
                ('pdf_doc', models.FileField(default='Untitled', upload_to='rjikm/uploads/')),
                ('is_archived', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(related_name='articles', to='rjikm.author')),
            ],
        ),
    ]
