# Generated by Django 4.0.1 on 2022-12-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListItem',
            new_name='editorialboard',
        ),
    ]
