# Generated by Django 4.0.1 on 2022-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0002_rename_listitem_editorialboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialboard',
            name='item',
        ),
        migrations.RemoveField(
            model_name='editorialboard',
            name='order',
        ),
        migrations.AddField(
            model_name='editorialboard',
            name='FirstName',
            field=models.CharField(default='Tom', max_length=100),
        ),
        migrations.AddField(
            model_name='editorialboard',
            name='SecondName',
            field=models.CharField(default='Kwanya', max_length=100),
        ),
    ]
