# Generated by Django 4.0.1 on 2022-12-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0003_remove_editorialboard_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialboard',
            name='Country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='editorialboard',
            name='Prefix',
            field=models.CharField(default='Prof', max_length=20),
        ),
        migrations.AddField(
            model_name='editorialboard',
            name='University',
            field=models.CharField(default='Technical University of Kenya', max_length=100),
        ),
    ]
