# Generated by Django 4.0.1 on 2022-12-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0004_editorialboard_country_editorialboard_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorinchief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='Tom', max_length=100)),
                ('University', models.CharField(default='Technical University of Kenya', max_length=100)),
                ('MyEmail', models.CharField(default='tom.kwanya@gmail.com', max_length=100)),
            ],
        ),
    ]
