# Generated by Django 4.0.1 on 2022-12-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0005_editorinchief'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorinchief',
            name='Department',
            field=models.CharField(default='Information and library Sciences', max_length=100),
        ),
    ]
