# Generated by Django 4.0.1 on 2022-12-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0007_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
