# Generated by Django 4.0.1 on 2022-12-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0008_alter_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Untitled', max_length=400),
        ),
    ]
