# Generated by Django 4.0.1 on 2022-12-22 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0009_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
