# Generated by Django 4.0.1 on 2022-12-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0010_alter_article_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(default='No abstract provided'),
        ),
    ]
