# Generated by Django 4.0.1 on 2022-12-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0011_alter_article_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titlelink',
            field=models.CharField(default='Untitled', max_length=400),
        ),
    ]
