# Generated by Django 4.0.1 on 2022-12-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0012_article_titlelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract_title',
            field=models.CharField(default='Abstract', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='keyword_title',
            field=models.CharField(default='Keyword', max_length=100),
        ),
    ]
