# Generated by Django 4.0.4 on 2022-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0013_article_abstract_title_article_keyword_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='articles/')),
            ],
        ),
    ]
