# Generated by Django 4.0.1 on 2022-12-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0014_submit_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_article',
            name='pdf_file',
            field=models.FileField(upload_to='rjikm/articles/'),
        ),
    ]
