# Generated by Django 4.0.1 on 2022-12-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0015_alter_submit_article_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit_article',
            name='pdf_file',
            field=models.FileField(upload_to='rjikm/uploads/'),
        ),
    ]
