# Generated by Django 4.0.4 on 2022-12-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0016_alter_submit_article_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
