# Generated by Django 4.0.1 on 2023-01-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0018_rename_author_article_author1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='titlelink',
        ),
    ]
