# Generated by Django 4.0.1 on 2023-01-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0019_remove_article_titlelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_doc',
            field=models.FileField(default='Untitled', upload_to='rjikm/static/pdf'),
        ),
    ]
