# Generated by Django 4.0.1 on 2023-01-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0020_article_pdf_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_doc',
            field=models.FileField(default='Untitled', upload_to='rjikm/uploads/'),
        ),
        migrations.AlterField(
            model_name='submit_article',
            name='pdf_file',
            field=models.FileField(upload_to='rjikm/submitted/'),
        ),
    ]
