# Generated by Django 4.0.1 on 2023-01-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0021_alter_article_pdf_doc_alter_submit_article_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author3',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='department3',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='email3',
            field=models.EmailField(default='anonymous@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='article',
            name='university3',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='submit_article',
            name='pdf_file',
            field=models.FileField(upload_to='rjikm/uploads/'),
        ),
    ]
