# Generated by Django 4.0.1 on 2023-01-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0022_article_author3_article_department3_article_email3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit_article',
            old_name='pdf_file',
            new_name='doc_file',
        ),
    ]
