# Generated by Django 4.2.9 on 2024-06-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjikm', '0023_rename_pdf_file_submit_article_doc_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Author Name', max_length=100)),
                ('university', models.CharField(default='Name of the University', max_length=100)),
                ('department', models.CharField(default='Name of the Department', max_length=100)),
                ('email', models.EmailField(default='Enter your email address', max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='department1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='department2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='department3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='email3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='university1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='university2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='university3',
        ),
        migrations.AddField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to='rjikm.author'),
        ),
    ]
